site_name: NovaIT
# добавляет линк тег в голову страниц и берет путь для serve
site_url: https://novait.com.ua/
# добавляет мета тег в хеадер с информацией
site_description: NovaIt documentation site_description
# добавляет мета тег в хеадер с информацией
site_author: NovaIt
# copyright: инфа добавляется в документацию темой

#Repository
# repo_url: делает линки на каждой странице
# remote_branch: gh-pages (ветка, куда будет комитить с помощью gh-deploy GitHub Pages)
# remote_name: origin (куда будет пушить с помощью gh-deploy)

# Станицы документации
nav:
    - Home: main.md
    - Release Notes:     
        - Nova.BotConnector: components/novabotconnector.md
        - Nova.BotFlow: components/novabotflow.md
        - Nova.ChatProxy: components/novachatproxy.md
        - Nova.ChatProxy.Cisco.ECE: components/novachatproxyciscoece.md
        - Nova.ChatProxy.Cisco.UCCX: components/novachatproxyciscouccx.md
        - Nova.ChatProxy.Genesys.PureCloud: components/novachatproxygenesyspurecloud.md
        - Nova.ChatProxy.Genesys.PureConnect.ICWS: components/novachatproxygenesyspureconnecticws.md
        - Nova.ChatProxy.Genesys.PureEngage.GMS.ChatAPIv2: components/novachatproxygenesyspureengagegmschatapiv2.md
        - Nova.ChatProxy.NovaIT.Chat24: components/novachatproxynovaitchat24.md
        - Nova.ChatRouter.Dialogflow: components/novachatrouterdialogflow.md
        - Nova.ChatRouter.Omilia: components/novachatrouteromilia.md
        - Nova.WebChat: components/novawebchat.md
    - Chatwoot: checklist.md

theme:
  name: null
  custom_dir: mkdocs-material/material

  # 404 page
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
#  icon:
#    logo: logo
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  logo: assets/icon.png
  favicon: images/favicon.png
  icon:
    logo: assets/icon.png

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true

extra:
  homepage: http://127.0.0.1:8000/components/novabotflow/#product-notices
  alternate:
    - name: English
      link: /en/ 
      lang: en
    - name: Russian
      link: /ru/
      lang: ru
    - name: Ukrainian
      link: /uk/
      lang: uk